[package]
name = "bf-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.5.8"
cranelift = "0.89"
target-lexicon = "0.12.5"

[features]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
