[build]
rustflags = ["-C", "target-cpu=native"]
rustdocflags = [
    "--cfg",
    "docsrs",
    "-Z",
    "unstable-options",
    "--show-type-layout",
]

[doc.extern-map.registries]
crates-io = "https://docs.rs/"
