[build]
rustflags = ["-C", "target-cpu=native"]
rustdocflags = [
    "--cfg",
    "docsrs",
    "-Z",
    "unstable-options",
    "--show-type-layout",
]
rustc-wrapper = "sccache.exe" # Uncomment this when using sccache

[doc.extern-map.registries]
crates-io = "https://docs.rs/"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
    "-Zshare-generics=y",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",
    "-Zshare-generics=y",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]

[profile.dev]
debug = 1
